name: build 360t7

on:
  #pull_request:
  workflow_dispatch:
  #push:
  #  branches: 
  #    - openwrt-22.03

jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
      - name: Install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: feeds
          path: feeds
